### ISSUE TITLE
Redis error? wrong number of arguments (given 3, expected 2):

### ISSUE THREAD

**Issue by jimmybaker** [Envek/graphql-anycable#9]
We've started noticing the following error:

```
[AnyCable sid=6a1Ro1nYeBkZQRCDYchRoc] wrong number of arguments (given 3, expected 2):
2.6.0/gems/redis-4.1.2/lib/redis.rb:1352:in `sadd'
2.6.0/gems/graphql-anycable-0.3.1/lib/graphql/subscriptions/anycable_subscriptions.rb:104:in `block in write_subscription'
2.6.0/gems/redis-4.1.2/lib/redis.rb:2461:in `block in multi'
2.6.0/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
2.6.0/monitor.rb:230:in `mon_synchronize'
2.6.0/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
2.6.0/gems/redis-4.1.2/lib/redis.rb:2454:in `multi'
2.6.0/gems/graphql-anycable-0.3.1/lib/graphql/subscriptions/anycable_subscriptions.rb:101:in `write_subscription'
2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:82:in `public_send'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:82:in `block in call_after_hooks'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:80:in `each'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:80:in `call_after_hooks'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:74:in `call_hooks'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
2.6.0/gems/graphql-1.9.17/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
 DEBUG 2020-03-02T22:28:25.819Z context=rpc Command response: error_msg:"wrong number of arguments (given 3, expected 2)"
```

In the version of redis we're using `sadd` only takes two arguments, but you're splatting the second argument which is causing this error. We're not sure what needs to be done here. Any help is appreciated.

**Comment by Envek** [comment]
Ouch! That was a dumb mistake!

We're using subscriptions with only one field so we didn't even noticed that. I added tests for that use case too.

Please grab version [0.3.3](https://rubygems.org/gems/graphql-anycable/versions/0.3.3) with the fix for you!

P.S> While I was searching around I found that graphql-ruby creator also did a similar mistake in the past (at least I'm not alone): https://github.com/rmosolgo/graphql-ruby/issues/1813

**Comment by Envek** [comment]
Okay, CI shows that you've opened a Pandora box here: it seems that subscriptions with multiple fields are broken in 1.10 if subscription classes are not used. So be careful when upgrading graphql-ruby (and write tests!). Related issue is here: https://github.com/rmosolgo/graphql-ruby/issues/2795
